apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: blue      # ← ابدأ بالـ blue، وعند التحويل غيّرها لـ green
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
